"""Validation package: reverification statistics and engine."""

from trading_platform.validation.engine import (
    ConfigResult,
    FamilyEvidence,
    family_level_diagnostics,
    validate_configuration,
)
from trading_platform.validation.reverification import (
    COST_STRESS_MULTIPLIERS,
    PurgedFold,
    benchmark_comparison,
    concentration,
    cost_stress_summary,
    parameter_stability_surface,
    purged_walk_forward_splits,
    regime_decomposition,
    verify_no_leakage,
)
from trading_platform.validation.statistics import (
    BootstrapConfig,
    annualized_return,
    bootstrap_distribution,
    calmar_ratio,
    cscv_pbo,
    deflated_sharpe_ratio,
    longest_drawdown_days,
    max_consecutive_losses,
    max_drawdown,
    probabilistic_sharpe_ratio,
    sharpe_ratio,
    sortino_ratio,
    trade_metrics,
    white_reality_check,
)

__all__ = [
    "BootstrapConfig",
    "COST_STRESS_MULTIPLIERS",
    "ConfigResult",
    "FamilyEvidence",
    "PurgedFold",
    "annualized_return",
    "benchmark_comparison",
    "bootstrap_distribution",
    "calmar_ratio",
    "concentration",
    "cost_stress_summary",
    "cscv_pbo",
    "deflated_sharpe_ratio",
    "family_level_diagnostics",
    "longest_drawdown_days",
    "max_consecutive_losses",
    "max_drawdown",
    "parameter_stability_surface",
    "probabilistic_sharpe_ratio",
    "purged_walk_forward_splits",
    "regime_decomposition",
    "sharpe_ratio",
    "sortino_ratio",
    "trade_metrics",
    "validate_configuration",
    "verify_no_leakage",
    "white_reality_check",
]
